export enum Genre {
    FICTION = 'Ficción',
    NON_FICTION = 'No ficción',
    FANTASY = 'Fantasía',
    SCIENCE_FICTION = 'Ciencia Ficción',
    MYSTERY = 'Misterio',
    HORROR = 'Terror',
    ROMANCE = 'Romance',
    ADVENTURE = 'Aventura',
    HISTORICAL = 'Histórico',
    BIOGRAPHY = 'Biografía',
    AUTOBIOGRAPHY = 'Autobiografía',
    POETRY = 'Poesía',
    DRAMA = 'Drama',
    ESSAY = 'Ensayo',
    CHILDRENS = 'Infantil',
    YOUNG_ADULT = 'Juvenil',
    SELF_HELP = 'Autoayuda',
    HUMOR = 'Humor',
    PHILOSOPHY = 'Filosofía',
    RELIGION = 'Religión',
    SCIENCE = 'Ciencia',
    TECHNOLOGY = 'Tecnología',
}